### ISSUE TITLE
本地测试报错

### ISSUE THREAD

**Issue by bobiscool** [YueChen-C/py-ios-device#1]
![image](https://user-images.githubusercontent.com/9073321/104011657-71003180-51e9-11eb-9fac-2c22ddee2386.png)
跑不起来呀
pip3 install 了

**Comment by YueChen-C** [comment]
使用 GitHub 源码吧， pip 仓库现在还没弄好

**Comment by bobiscool** [comment]
现在发现有新一个问题  就是我设置了deviceid  获取网络状态 和所有进程性能数据貌似返回的都是None   是使用方法不对吗

YueC <notifications@github.com>于2021年1月11日 周一下午2:37写道：
