### ISSUE TITLE
server > mc_install.py > MCInstallService().install_profile()

### ISSUE THREAD

**Issue by linyajun558** [YueChen-C/py-ios-device#100]
这个方法是用来安装安装证书描述文件的吗？例如抓包的证书
    def install_profile(self, payload):
        self.service.send_plist({'RequestType': 'InstallProfile', 'Payload': payload})
        return self.service.recv_plist()
payload应该传什么？方便解答一下么？我想通过这个方法给手机安装可信任证书，可行么？

**Comment by YueChen-C** [comment]
`pyidevice profiles install  --path Downloads/charles-certificate.pem`
