### ISSUE TITLE
[Bug] Turn developer mode on on ios 16 + devices

### ISSUE THREAD

**Issue by sanidhya-saraswat** [YueChen-C/py-ios-device#103]
When we try to turn on developer mode, on ios16+ devices, using the command
`pyidevice enable_developer_mode`
we get error like
`Exception: enable_developer_mode_turn_on {'Error': 'An unknown error has occured'}`

Anyway to get over this ?

**Comment by YueChen-C** [comment]
`enable_developer_mode_turn_on` This method is used to click the confirmation button after the device restarts.
