### ISSUE TITLE
Developer Image path

### ISSUE THREAD

**Issue by khrithik96** [YueChen-C/py-ios-device#104]
The endpoint used to download the developer image has been updated.

The path mentioned in https://github.com/YueChen-C/py-ios-device/blob/7697ebb941658061247199494ea36d10145a79e7/ios_device/util/lockdown.py#L315: `https://github.com/JinjunHan/iOSDeviceSupport/raw/master/DeviceSupport/` does not exist anymore.

The updated path is `https://github.com/JinjunHan/iOSDeviceSupport/raw/master/iOSDeviceSupport/`

**Comment by YueChen-C** [comment]
Thanks.
