### ISSUE TITLE
Intermittent error during app listing

### ISSUE THREAD

**Issue by khrithik96** [YueChen-C/py-ios-device#107]
Getting error `'NoneType' object has no attribute 'get'` when calling `get_apps` of `InstallationProxyService`.

`self.service.recv_plist()` is returning `None` intermittently, which is causing the error.

https://github.com/YueChen-C/py-ios-device/blob/4dddce914ff885082f578912fff882b8b06a84e4/ios_device/servers/Installation.py#L148

Getting this error intermittently only on one device: iPhone SE2, iOS 15.5.

Any idea how can this be fixed?

**Comment by YueChen-C** [comment]
用 debug 模式运行能看到更多日志，目前这么看，不知道怎么查。

**Comment by YueChen-C** [comment]
https://github.com/YueChen-C/py-ios-device/blob/4dddce914ff885082f578912fff882b8b06a84e4/ios_device/util/plist_service.py#L84-L86

Looks more like the device disconnected and then reconnected

**Comment by khrithik96** [comment]
We were not able to reproduce the error. For now, we have added a retry.
