### ISSUE TITLE
请问获取单应用的性能数据，各个数据的单位是什么呢？

### ISSUE THREAD

**Issue by OneCat08** [YueChen-C/py-ios-device#108]
请问获取单应用的性能数据，各个数据的单位是什么呢？比如内存大小有12位数，想转换成MB，按照最小单位转化都不太合理
{'memVirtualSize': 419539484672, 'cpuUsage': 0.7302214451526017}

**Comment by YueChen-C** [comment]
用新的的命令 2.3.32 版本 pyidevice instruments appmonitor  -b cn.rongcloud.im
