### ISSUE TITLE
How to obtain memory used by pid like Instruments app

### ISSUE THREAD

**Issue by morellexf13** [YueChen-C/py-ios-device#113]
- Device: iPhoneXS
 - OS: iOS16.5
 - Pyidevice Version: 2.3.2

When I use Instruments app (screenshot below) I can see that my app is using **68,77 MiB**. On _pyidevice_, how can I access this field? What's the name? I'm currently using the `memResidentSize` but the value is different/greater (122257408 Bytes). So apparently it's the wrong one.

<img width="941" alt="Captura de pantalla 2023-06-19 a la(s) 11 52 51" src="https://github.com/YueChen-C/py-ios-device/assets/73654994/9c0a3eea-9730-4b46-8e92-7f3d67b618ca">

**Comment by YueChen-C** [comment]
use `physFootprint`
