### ISSUE TITLE
使用pyidevice instruments monitor 时，拿到的memory 数据是负数，free memory甚至越用越大。

### ISSUE THREAD

**Issue by xhsndsy** [YueChen-C/py-ios-device#117]
**Smartphone (please complete the following information):**
 - Device: [e.g. iPad mini6]
 - Pyidevice Version [e.g. 2.2.0]

**Describe the bug**

用pyidevice instruments monitor 时，拿到的memory 数据是负数，free memory甚至越用越大。
在用 pyidevice instruments appmonitor  -b 包名 时，会报这个

>   File "C:\Users\admin\venv\lib\site-packages\click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\admin\venv\lib\site-packages\click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\admin\venv\lib\site-packages\click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Users\admin\venv\lib\site-packages\click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Users\admin\venv\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\admin\venv\lib\site-packages\click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\Users\admin\venv\lib\site-packages\ios_device\cli\instruments.py", line 192, in cmd_appmonitor
>     name = app.get('ExecutableName')
> AttributeError: 'list' object has no attribute 'get'
>

**Comment by YueChen-C** [comment]
发布版本 2.3.32.5
