### ISSUE TITLE
请问从com.apple.instruments.server.services.sysmontap拿到得数据是否有统一处理方法

### ISSUE THREAD

**Issue by lezhi12** [YueChen-C/py-ios-device#119]
**Smartphone (please complete the following information):**
 - OS: [e.g. iOS12.1]
 - Pyidevice Version [e.g. 2.2.0]

**Describe the bug**
想使用咱们这个工具，但是有个问题比较有顾虑，就是从com.apple.instruments.server.services.sysmontap拿到得性能数据，如果不是直接用得话，需要经过何种计算？这种计算方式是从哪里获得（可能不同的ios系统还存在兼容问题）？与MAC上启动XCODE的activity monitor，获得的数据是否一致？

**Comment by YueChen-C** [comment]
可以参考 cli 命令行例子，里面都有
