### ISSUE TITLE
python 3.10.3 安装 py_ios_device报错

### ISSUE THREAD

**Issue by Sgr-Ice** [YueChen-C/py-ios-device#120]
- [x] You have checked the submission history of issues and discussions
- [x] It is best to use [discussions](https://github.com/YueChen-C/py-ios-device/discussions) to ask questions

![image](https://github.com/YueChen-C/py-ios-device/assets/89150750/cdba0287-c37a-497f-8c03-c1a03fd9e461)

![image](https://github.com/YueChen-C/py-ios-device/assets/89150750/c1c691e6-74f0-4388-9067-1adf78da5e90)

error: subprocess-exited-with-error
error: metadata-generation-failed

**Comment by YueChen-C** [comment]
看起来和库关系不大 试着更新 pip 或者 setuptools 试下

**Comment by yameishijianong** [comment]
我的pip版本更新到最新的：Version: 23.2.1
setuptools：68.0.0
还是跟上面老哥的一样，会报同样的错

**Comment by YueChen-C** [comment]
没看到具体错误内容是什么

**Comment by xhsndsy** [comment]
遇到过，已安装的组件与现在要安装的组件冲突了。试试用全新的虚拟环境试试，应该没有问题
