### ISSUE TITLE
pyidevice instruments fps does not show fps above 60.

### ISSUE THREAD

**Issue by homurahomu1** [YueChen-C/py-ios-device#121]
**Smartphone (please complete the following information):**
 - Device: [iPhone13ProMax]
 - OS: [iOS16.6]
 - Pyidevice Version [v2.3.2]

**Describe the bug**

<img width="682" alt="Screenshot 2023-08-13 at 6 41 35 pm" src="https://github.com/YueChen-C/py-ios-device/assets/69967456/29b0aac6-2dd3-4ea1-9475-7b81f185fedf">

**pyidevice instruments fps** _does not show any fps above 60_. If the display is at 120 or 80hz and the app or game is running at 120fps or 80fps, the feed still keeps showing "{'currentTime': '2023-08-13 18:40:51.106487', 'fps': 60}".

**Comment by YueChen-C** [comment]
If you use the system graphics.opengl service, the maximum is only 60 fps.

You can use the coreprofilesessionap.py in the demo folder for more advanced calculation methods
