### ISSUE TITLE
大佬，readme手册里的命令执行的参数有问题

### ISSUE THREAD

**Issue by CCodeInspect** [YueChen-C/py-ios-device#128]
![image](https://github.com/YueChen-C/py-ios-device/assets/44918169/d93d3af5-5d88-4f54-93a8-79a45f55097e)
这样才能执行pyidevice instruments monitor --filter memory
![image](https://github.com/YueChen-C/py-ios-device/assets/44918169/4ef3c51b-f27f-405f-9fe5-8c9abb1404e7)

**Comment by YueChen-C** [comment]
去掉= 旁边的空格就可以
