### ISSUE TITLE
iOS17的屏幕帧数获取在windows上存在延迟。

### ISSUE THREAD

**Issue by FewL** [YueChen-C/py-ios-device#133]
这个问题只在windows平台上存在。
以下是`./demo/instrument_demo/coreprofilesessiontap.py`中`graphics_display`函数的部分输出：
> set None
> start <ios_device.util.exceptions.InstrumentRPCParseError object at 0x00000203D670AFB0>
> 17.98817491531372 FPS: 48.971765736562624 jank: 0 big_jank: 0 stutter: 0.0
> 26.098522901535034 FPS: 58.99339327253272 jank: 0 big_jank: 0 stutter: 0.0
> 35.51827001571655 FPS: 59.087249710103194 jank: 0 big_jank: 0 stutter: 0.0
> 45.445099115371704 FPS: 58.988030345509046 jank: 0 big_jank: 0 stutter: 0.0
> 53.08789110183716 FPS: 58.92447846010696 jank: 0 big_jank: 0 stutter: 0.0
> 64.4722580909729 FPS: 57.97999931606926 jank: 0 big_jank: 0 stutter: 0.0
> 75.11655592918396 FPS: 58.047693723314374 jank: 0 big_jank: 0 stutter: 0.0
> 82.75758099555969 FPS: 59.93323437690412 jank: 0 big_jank: 0 stutter: 0.0

根据输出逻辑（line#36-line#71），数据接收的时间有明显的延迟，接着直接打印事件时间，发现并没有丢包：
`print(f"PC: {datetime.now().timestamp()} Mach: {_time * mach_time_factor}")`

> PC: 1709706900.87253 Mach: 73043993834916.66
> PC: 1709706902.890603 Mach: 73044012638208.33
> PC: 1709706902.891576 Mach: 73044027172666.66
> PC: 1709706902.891576 Mach: 73044045435208.33
> PC: 1709706902.892587 Mach: 73044061449166.66
> PC: 1709706902.893649 Mach: 73044078227125.0
> PC: 1709706902.893649 Mach: 73044094062291.66
> PC: 1709706902.894576 Mach: 73044111848291.66
> PC: 1709706902.894576 Mach: 73044128488958.33
> PC: 1709706902.894576 Mach: 73044144104250.0
> PC: 1709706902.895588 Mach: 73044162283708.33
> PC: 1709706902.895588 Mach: 73044177343833.33
> PC: 1709706902.895588 Mach: 73044195655083.33
> PC: 1709706902.896575 Mach: 73044210676208.33
> PC: 1709706904.955388 Mach: 73044227457791.66
> PC: 1709706904.955388 Mach: 73044245023541.66
> PC: 1709706904.956358 Mach: 73044260169166.66
> PC: 1709706904.956358 Mach: 73044280137500.0
> PC: 1709706904.956358 Mach: 73044295324458.33
> PC: 1709706904.957356 Mach: 73044312685375.0
> PC: 1709706904.957356 Mach: 73044329304750.0
> PC: 1709706904.957356 Mach: 73044345196625.0
> PC: 1709706904.958355 Mach: 73044360302166.66
> PC: 1709706904.958355 Mach: 73044378675458.33
> PC: 1709706904.958355 Mach: 73044395742833.33
> PC: 1709706904.958355 Mach: 73044410714625.0
> PC: 1709706904.959356 Mach: 73044427484875.0
> PC: 1709706907.014738 Mach: 73044446020083.33
> PC: 1709706907.015708 Mach: 73044461635625.0
> PC: 1709706907.015708 Mach: 73044478274791.66
> PC: 1709706907.016725 Mach: 73044494829541.66
> PC: 1709706907.016725 Mach: 73044511669541.66
> PC: 1709706907.017712 Mach: 73044528291708.33
> PC: 1709706907.017712 Mach: 73044544620000.0
> PC: 1709706907.018721 Mach: 73044560723416.66
> PC: 1709706907.018721 Mach: 73044578174416.66
> PC: 1709706907.019714 Mach: 73044595248750.0
> PC: 1709706907.019714 Mach: 73044611219916.66
> PC: 1709706907.020707 Mach: 73044628924125.0
> PC: 1709706907.020707 Mach: 73044644166541.66
> PC: 1709706908.952827 Mach: 73044660899416.66
> PC: 1709706908.953827 Mach: 73044679200083.33
> PC: 1709706908.953827 Mach: 73044695148625.0
> PC: 1709706908.954874 Mach: 73044711602666.66
> PC: 1709706908.954874 Mach: 73044727274875.0
> PC: 1709706908.954874 Mach: 73044745234958.33
> PC: 1709706908.955827 Mach: 73044761639791.66
> PC: 1709706908.955827 Mach: 73044777209000.0
> PC: 1709706908.955827 Mach: 73044794479000.0
> PC: 1709706908.955827 Mach: 73044812103541.66
> PC: 1709706908.956829 Mach: 73044827368916.66
> PC: 1709706908.956829 Mach: 73044845023125.0
> PC: 1709706908.956829 Mach: 73044861905291.66
> PC: 1709706910.675515 Mach: 73044878766625.0
> PC: 1709706910.676469 Mach: 73044894236416.66
> PC: 1709706910.676469 Mach: 73044912302583.33
> PC: 1709706910.677478 Mach: 73044927618500.0
> PC: 1709706910.677478 Mach: 73044945383291.66
> PC: 1709706910.678469 Mach: 73044961311833.33
> PC: 1709706910.678469 Mach: 73044977226916.66
> PC: 1709706910.678469 Mach: 73044994208458.33
> PC: 1709706910.679475 Mach: 73045012700500.0

PC需要10秒的时间才接收完设备1秒内发送的数据。

所有数据用15Pro（17.2）在Camera 4K 60Hz视频下测得。

**Comment by YueChen-C** [comment]
也许是通道的问题？数据量太大堵塞了吗？

**Comment by FewL** [comment]
> 也许是通道的问题？数据量太大堵塞了吗？

应该是的，这是驱动的问题吗？

**Comment by ruokbb** [comment]
这个有什么解决办法吗？

**Comment by YueChen-C** [comment]
建议使用 go-ios 创建的隧道
