### ISSUE TITLE
support screencap on ios>17

### ISSUE THREAD

**Issue by AmazingRaise** [YueChen-C/py-ios-device#142]
- [x] You have checked the submission history of issues and discussions
- [x] It is best to use [discussions](https://github.com/YueChen-C/py-ios-device/discussions) to ask questions

tried [screenshotr.py](https://github.com/YueChen-C/py-ios-device/blob/main/demo/screenshotr.py),seems not work

**Comment by YueChen-C** [comment]
https://github.com/YueChen-C/py-ios-device/issues/139

**Comment by AmazingRaise** [comment]
got it, However more than 2s one time on iPhone 15 pro max
