### ISSUE TITLE
在Linux环境下执行pyidevice instruments stackshot --out 123.log报错，win环境下OK

### ISSUE THREAD

**Issue by 986379041** [YueChen-C/py-ios-device#148]
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone14]
 - OS: [e.g. iOS16]
 - Pyidevice Version [e.g. 2.3.2]

**Describe the bug**
ValueError: Invalid version. The only valid version for X509Req is 0.

**Comment by YueChen-C** [comment]
这个跟 python 版本有关系，可以用最新版 pyidevice 2.4.15 或者 python 3.9 以下
