### ISSUE TITLE
CoreProfileSessionTap方式计算得到的FPS不准

### ISSUE THREAD

**Issue by xlhe3** [YueChen-C/py-ios-device#153]
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone15pro]
 - OS: [e.g. iOS17.6]
 - Pyidevice Version [e.g. 2.3.2]

**Describe the bug**
同时触发
短的来自于GraphicsOpengl   CoreAnimationFramesPerSecond直接得到
长的来自于CoreProfileSessionTap  然后计算得到
结果是2者有明显差异，请大神帮忙看看，我在60上验证，然后准备是用第二种方式去测120FPS的，但目前在120FPS上也只是117左右。

{'PerfTime': 1, 'FPS': 58}
{'PerfTime': 2, 'FPS': 60}
{'time': 2.583245038986206, 'fps': 56.97050826688718}
{'PerfTime': 3, 'FPS': 58}
{'time': 3.5344700813293457, 'fps': 55.98916143149956}
{'PerfTime': 4, 'FPS': 59}
{'time': 4.480035066604614, 'fps': 57.031594028136574}
{'PerfTime': 5, 'FPS': 60}
{'time': 5.470026016235352, 'fps': 59.97174581125468}
{'PerfTime': 6, 'FPS': 59}
{'time': 6.7305309772491455, 'fps': 58.04817678916596}

**Comment by YueChen-C** [comment]
python 的计算性能会有一定的影响，这个数据量还是比较庞大的

**Comment by YueChen-C** [comment]
建议使用 go-ios 的隧道，性能高很多
