### ISSUE TITLE
ios17不支持命令行，现在获取单个app的性能数据要怎么使用呢

### ISSUE THREAD

**Issue by luoxiao1008** [YueChen-C/py-ios-device#154]
- [x] You have checked the submission history of issues and discussions
- [x] It is best to use [discussions](https://github.com/YueChen-C/py-ios-device/discussions) to ask questions

**Comment by YueChen-C** [comment]
去看下 cli 里面的实现吧，照着抄一下

**Comment by YueChen-C** [comment]
https://github.com/YueChen-C/py-ios-device/blob/a80647c77617ecda909d654fa3cc5153cd033db4/ios_device/cli/instruments.py#L163
