### ISSUE TITLE
Availability of Performance Data for iOS Tunnel Created in Userspace Mode

### ISSUE THREAD

**Issue by myungkyojung** [YueChen-C/py-ios-device#157]
Can performance data be retrieved when creating a tunnel using **ios tunnel start --userspace** instead of sudo ios tunnel start?
Or are there any plans for further development?

**Comment by YueChen-C** [comment]
Let me study it

**Comment by myungkyojung** [comment]
Thanks.

**Comment by YueChen-C** [comment]
```python
# ios tunnel start --userspace
# [{"address":"fd17:cafe:59d4::1","rsdPort":54934,"udid":"00008101-0018242C3XXXXXXXXX","userspaceTun":true,"userspaceTunPort":60106}]

host = 'fd17:cafe:59d4::1'
port = 54934  
with RemoteLockdownClient((host, port), userspace_port=60106) as rsd:
    rpc = InstrumentServer(rsd).init()
    sysmontap(rpc)
    rpc.stop()
```

**Comment by myungkyojung** [comment]
I just tested it, and the attached code works properly.
Has everything been implemented for performance information(cpu, memory, network...) retrieval?
Also, do you have any plans to support a CLI for iOS 17?"

**Comment by YueChen-C** [comment]
I don't want to spend too much time supporting the CLI...

**Comment by myungkyojung** [comment]
@YueChen-C 
I am writing a python script to retrieve performance information for iOS 17.  
Should I explicitly release the RemoteLockdownClient and InstrumentServer objects when receiving SIGINT or SIGTERM signals for a graceful shutdown, or will they be automatically released when the script terminates?

**Comment by YueChen-C** [comment]
RemoteLockdownClient connections can be reused by multiple InstrumentServers.

Some InstrumentServers services can only enable one , otherwise it will affect the system operation such as `com.apple.instruments.remoteserver.DVTSecureSocketProxy`.
I recommend releasing it immediately after use

**Comment by myungkyojung** [comment]
@YueChen-C 
In the code with RemoteLockdownClient((args.host, args.port), userspace_port=args.userspace_port) as rsd:, the creation of the RemoteLockdownClient object takes a long time. How can I improve its performance?

**Comment by YueChen-C** [comment]
During this period, pairing and establishing a new connection are required.
I can't give any new suggestions for now.

**Comment by myungkyojung** [comment]
@YueChen-C  Thank you for your answer.
