### ISSUE TITLE
iOS 17以上系统获取icon png data问题

### ISSUE THREAD

**Issue by lycfr** [YueChen-C/py-ios-device#159]
<img width="584" alt="image" src="https://github.com/user-attachments/assets/ed671cd0-e240-4e0c-a127-78397a479e6e">

使用设备iPhone 15  系统：17.1

使用最新的py-ios-device获取时候提示异常，然后我把py-ios-device降到2.4.10能获取到。还是用的比较老的版本，还没仔细看最新版本的代码，暂时没解决这个问题是咋回事，但是低版本能获取，高版本应该也是可以才对

**Comment by YueChen-C** [comment]
已修改
