### ISSUE TITLE
如何发现入参的

### ISSUE THREAD

**Issue by ZackZZZZZ** [YueChen-C/py-ios-device#2]
请教一下，我用ida反汇编库文件发现com.apple.instruments.server.services.sysmontap服务对应的DTTapService类里面的setConfig:方法并没有太多的源码可供参考，请问是如何发现setConfig:方法的入参的

**Comment by YueChen-C** [comment]
这个主要通过解析 instruments 与设备之间交互数据包，来分析入参数据。

**Comment by ZackZZZZZ** [comment]
用什么软件可以捕获到iOS设备的数据包，Wireshark或者Charles可以吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YueChen-C/py-ios-device"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 下午5:45
收件人:&nbsp;"YueChen-C/py-ios-device"<py-ios-device@noreply.github.com&gt;;
抄送:&nbsp;"我写完这段就来～"<1093758932@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YueChen-C/py-ios-device] 如何发现入参的 (#2)





 
这个主要通过解析 instruments 与设备之间交互数据包，来分析入参数据。

**Comment by YueChen-C** [comment]
mac上 Wireshark 或者 Charles 抓不到，需要中间人unix代理工具
readme 有介绍，也有里面也有我的文章，可以自己试下

**Comment by ZackZZZZZ** [comment]
万分感谢
