### ISSUE TITLE
怎样查询app是否杀死？

### ISSUE THREAD

**Issue by wgywgy** [YueChen-C/py-ios-device#27]
看readme里提供查询 运行状态，不知道具体用什么命令执行

**Comment by YueChen-C** [comment]
`pyidevice instruments runningProcesses --format=json` 这能看当前正在运行的app

`pyidevice instruments notifications` 这个能监听 app 退到后台，杀死，启动，重启等

**Comment by wgywgy** [comment]
感谢，解决了我的问题
