### ISSUE TITLE
请问之后会支持文件系统么？比如某个应用下的指定目录之类的。

### ISSUE THREAD

**Issue by yyjxx2010xyu** [YueChen-C/py-ios-device#28]

**Comment by YueChen-C** [comment]
查看 app 沙箱数据吗？
```
>> pyidevice apps shell -b cn.rongcloud.im
AFC$ / cd Documents
AFC$ /Documents ls
.
..
rc0727170319.log
wpkdata

```

**Comment by felixruan** [comment]
> 

这里面的文件如何下载下来？pyidevice 有对应的pull文件方式吗

**Comment by felixruan** [comment]
> 查看 app 沙箱数据吗？
> 
> ```
> >> pyidevice apps shell -b cn.rongcloud.im
> AFC$ / cd Documents
> AFC$ /Documents ls
> .
> ..
> rc0727170319.log
> wpkdata
> ```

这里面的文件如何下载下来？pyidevice 有对应的pull文件方式吗
