### ISSUE TITLE
咨询个问题，这个获取内存的数据用虚拟内存数据么？这个数据好像不是真实的内存数据

### ISSUE THREAD

**Issue by pxrgod** [YueChen-C/py-ios-device#34]
[('WeChat', {'cpuUsage': 0.03663705586691998, 'memVirtualSize': 2179284992, 'name': 'WeChat', 'pid': 99269})]

**Comment by YueChen-C** [comment]
这个自己传参数，如果不加--proc_filter 会返回所有，实际上 physFootprint 这个和 instrument 几乎一样
> pyidevice instruments sysmontap  -b com.tencent.xin --processes
> pyidevice instruments sysmontap  -b com.tencent.xin --proc_filter physFootprint,cpuUsage --processes
