### ISSUE TITLE
您好咨询个问题，关于获取应用内存

### ISSUE THREAD

**Issue by Rladmsrl** [YueChen-C/py-ios-device#35]
您好 我想在获取start_get_graphics_fps中fps的同时传一个包名获取这个应用的内存占用，看了下demo中好像没有查看内存相关的，源码又捋不太清楚，能帮忙提供下思路么谢谢

**Comment by YueChen-C** [comment]
获取系统和应用内存相关的 用这个 start_get_system 
怎么过滤，你可以看 cli 里面的过滤方法 
https://github.com/YueChen-C/py-ios-device/blob/167da05eaaec7046a23285263ee425910096592d/ios_device/cli/instruments.py#L154

```
channel = init()
def callback1 (res):
    print(res)

def callback2(res):
    print(res[0]["PerCPUUsage"])
rpc_channel = start_get_graphics_fps(callback=callback1)
time.sleep(2)
system = start_get_system(callback=callback2, rpc_channel=rpc_channel)
time.sleep(10)```

**Comment by Rladmsrl** [comment]
多谢
