### ISSUE TITLE
你好 为什么抛出来个404

### ISSUE THREAD

**Issue by Caoyongqi912** [YueChen-C/py-ios-device#37]
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/filsv/iPhoneOSDeviceSupport/raw/master/DeviceSupport/14.7.zip

**Comment by Caoyongqi912** [comment]
运行这条命令 pyidevice instruments monitor

**Comment by Caoyongqi912** [comment]
不好意思 网络未翻墙的问题。
ValueError: math domain error
这个是因为啥呢 大佬

**Comment by YueChen-C** [comment]
因为调试 iOS 需要 DeviceSupport ，这个链接失效了我再找个链接，你也可以自行下载 相关版本 的开发者包放置在 
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/
或者 windows 
%USERPROFILE%/.py_ios_device/device-support

**Comment by Caoyongqi912** [comment]
大佬之前的问题搞定了。 对后有一个问题 'memVirtualSize': 5286526976, 'pid': 379, 'cpuUsage': 1.92494462221824})]
 这是我通过命令获取的数据， 我最这个内存与cpu 单位不大理解

**Comment by Caoyongqi912** [comment]
> 因为调试 iOS 需要 DeviceSupport ，这个链接失效了我再找个链接，你也可以自行下载 相关版本 的开发者包放置在
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/
> 或者 windows
> %USERPROFILE%/.py_ios_device/device-support
大佬之前的问题搞定了。 对后有一个问题 'memVirtualSize': 5286526976, 'pid': 379, 'cpuUsage': 1.92494462221824})]
这是我通过命令获取的数据， 我最这个内存与cpu 单位不大理解

**Comment by NISHAYANI** [comment]
'memVirtualSize': 5286526976, 'pid': 379, 'cpuUsage': 1.92494462221824
 这个内存与cpu 单位不大理解，这个能帮忙解答一下吗
