### ISSUE TITLE
apps launch 失败

### ISSUE THREAD

**Issue by SundaySundae** [YueChen-C/py-ios-device#48]
![image](https://user-images.githubusercontent.com/93760521/140473508-1fed573c-a6b7-4bc4-9783-78c7f2054a1a.png)

apps kill 表现正常，但launch报错，手机版本14.4.2 iPhoneXs，是否是适配问题。

**Comment by YueChen-C** [comment]
fix:278391c34576714a733c9061e4f26997c9893a1d
有点bug 已处理
