### ISSUE TITLE
Question regarding network conditions profiles

### ISSUE THREAD

**Issue by thedude4ever** [YueChen-C/py-ios-device#55]
Hello,

I wonder if it's possible to customize or create new network condition profiles, or if we are limited to the existed ones only (for example _SlowNetworkLTE_) ?

Thank you very much

**Comment by YueChen-C** [comment]
Tis is the function of xcode conditions ,It does not have the function of customize condition profiles
h
![image](https://user-images.githubusercontent.com/12081262/148530573-8506f8a1-f165-4388-8632-67adbfe9810e.png)
