### ISSUE TITLE
How to interpret memory result

### ISSUE THREAD

**Issue by thedude4ever** [YueChen-C/py-ios-device#60]
Hi  @YueChen-C 

could you please explain the meaning of each value after following command : _$  pyidevice instruments monitor --filter 'memory'

I'm a little bit lost because when I do the test on an iphone, without any launched application and just after a reboot I've got a free memory very low, I don't understand : 

_Memory  >> {'App Memory': '975.77 MiB', '**Free Memory': '69.72 MiB**', 'Cached Files': '1.71 GiB', 'Compressed': '0.00 Bytes', 'Memory Used': '1.87 GiB', 'Wired Memory': '554.39 MiB', 'Swap Used': '0.00 Bytes'}_

Thanks a lot

**Comment by YueChen-C** [comment]
I guess the iPhone doesn't allocate a lot of "free memory" when it's not in use.
When an application is launched and then killed, "free memory" is allocated and reserved.
