### ISSUE TITLE
Meaning of kdebug args.code profiling janks

### ISSUE THREAD

**Issue by franpandol** [YueChen-C/py-ios-device#62]
Hello Yue, great lib btw, I've been using it a lot. May I ask you a few things about start_get_fps ? 

I'm trying to measure Janks but I don't know what these codes mean. For example, why do you start coreprofilession using these filters , and what do they mean. ?

630784000, 833617920, 830472456 in this snippet

```
    _rpc_channel.call("com.apple.instruments.server.services.coreprofilesessiontap", "setConfig:",
        {'rp': 10,
         'tc': [{'kdf2': {630784000, 833617920, 830472456},
         'tk': 3,
         'uuid': str(uuid.uuid4()).upper()}],
         'ur': 500})

````

And why do you check for 830472984 to do the math for janks ?

````

          for args in Kperf.to_dict(res.selector.data):
              _time, code = args.timestamp, args.debug_id
              if code == 830472984:
                  if not last_frame:
                      last_frame = long(_time)
                  else:

````

If you could guide me a little bit with this it will be super helpful. Thanks a lot Yue. Great work!

**Comment by YueChen-C** [comment]
The coreprofilesessiontap service returns kernel log data . It also contains GUP kernel data

830472984 is not the unique value used to the math for Jank. you can use kperf.to_str to print detailed information e.g.
```python
  for args in Kperf.to_str(res.selector.data):
      print(args)
```

You could download Apple opensource [xnu-7195.81.3.tar.gz](https://opensource.apple.com/tarballs/xnu/xnu-7195.81.3.tar.gz)  --> xnu-7195.81.3/bsd/kern/kdebug.c  contains some code parsing methods
