### ISSUE TITLE
Unable to use py-ios-device on m1 mac

### ISSUE THREAD

**Issue by kandji-joel** [YueChen-C/py-ios-device#69]
When installing via poetry, cryptography==3.3.2 (which is required by py-ios-device) fails to install on m1 mac. I can install on intel mac without problem. It looks like the m1 mac is trying to install 37.0.2 of cryptography

**Comment by kandji-joel** [comment]
@YueChen-C any thoughts on this?

**Comment by YueChen-C** [comment]
I think we can delete the cryptography dependence, because pyOpenSSL will install the latest Cryptography (cryptography>=35.0)

**Comment by kandji-joel** [comment]
Related ^ https://stackoverflow.com/a/66055389
