### ISSUE TITLE
请问start_get_fps为什么判断code == 830472984？这部分数据有相关文档吗？

### ISSUE THREAD

**Issue by moclin** [YueChen-C/py-ios-device#74]
请问start_get_fps为什么判断code == 830472984？这部分数据有相关文档吗？

**Comment by YueChen-C** [comment]
这不是一个唯一值，是一个代表值，代表了 gpu 返回的数据 ，iOS 11 版本什么的这个值也会变化，code 怎么解析可以看
苹果开源 https://github.com/apple-oss-distributions/xnu
