### ISSUE TITLE
-t parameter not working for sysmontop

### ISSUE THREAD

**Issue by sanidhya-saraswat** [YueChen-C/py-ios-device#78]
command: `sysmontap`
parameter: `-t `/ `--time`

Issue: Parameter not working. Even after passing -t as 100, I am still getting output at 1000ms intervals.

Command I ran: ` pyidevice instruments sysmontap -t 100 -b com.google.ios.youtubemusic --proc_filter memVirtualSize,cpuUsage --processes --sort cpuUsage`

**Comment by YueChen-C** [comment]
already fixed, thx

**Comment by sanidhya-saraswat** [comment]
Please release the updated `pip` package too. Thanks

**Comment by YueChen-C** [comment]
use 2.2.3.8

**Comment by YueChen-C** [comment]
just updated
