### ISSUE TITLE
Anyway to get app startup time from this library ?

### ISSUE THREAD

**Issue by sanidhya-saraswat** [YueChen-C/py-ios-device#79]

**Comment by YueChen-C** [comment]
Not open source yet.

**Comment by YueChen-C** [comment]
I have open source this module . https://github.com/YueChen-C/py-ios-device/commit/230610120e2915ae35c1cf2060a1a7854020a050

**Comment by sanidhya-saraswat** [comment]
Closing the issue then.

**Comment by dipcse07** [comment]
Agreed....

**Comment by sanidhya-saraswat** [comment]
@YueChen-C one more thing to ask, but can you also add datetime in each log statement here?
<img width="637" alt="Screenshot 2023-02-16 at 1 34 36 PM" src="https://user-images.githubusercontent.com/21276981/219305404-30481551-fa56-451f-879c-6604ca3b7147.png">
