### ISSUE TITLE
求助-获取iOS设备的内存整体使用状况

### ISSUE THREAD

**Issue by linmscat** [YueChen-C/py-ios-device#8]
如何获取iOS设备的总内存大小，和可用内存大小 @YueChen-C @xiaochaom

**Comment by linmscat** [comment]
"351": [
                351,            // pid 
                417710325760,   // memVirtualSize
                770048,         // memResidentSize
                0.0,            // cpuUsage
                528,
                -82,            
                934232,         // physFootprint
                819200,         // memAnon
                0.0,            // powerScore
                708608          // diskBytesRead
            ],
这里面memVirtualSize、memResidentSize、memAnon这三个字段分别代表什么信息呢 @YueChen-C @xiaochaom

**Comment by YueChen-C** [comment]
如果查看内存的话，physFootprint 这个应该是比较准确的应用使用内存。memVirtualSize、memResidentSize 对应虚拟内存的大小，映射到物理内存的大小

**Comment by linmscat** [comment]
> 如果查看内存的话，physFootprint 这个应该是比较准确的应用使用内存。memVirtualSize、memResidentSize 对应虚拟内存的大小，映射到物理内存的大小

要获取iOS设备总的内存大小，需要用哪个字段 @YueChen-C

**Comment by bobzzb** [comment]
请问sysmontap里的 cpuUsage 和Xcode里看到的不一致，以那个为准啊

**Comment by YueChen-C** [comment]
cpuUsage 要从新计算的，需要除以当前使用 cpu 数量，需要根据具体情况进行二次计算。ios 14  以上好像又不用从新计算 @bobzzb

**Comment by YueChen-C** [comment]
我也没找到 iOS 设备总的内存大小相关信息 @linmscat

**Comment by su9695** [comment]
cpuUsage二次计算之后和 PerfDog 监控的值好像也不是太一致， cupUsage 是 拿（本次的 cpuTotalUser -上次取样的cpuTotalUser）/ (本次总cpu -上次总cpu)  这样计算的吗？  总cpu 的值是怎么取得 ? 所有线程的总和？
