### ISSUE TITLE
[appium][installCertificate] driver execute_script downloads certificate but not installing it

### ISSUE THREAD

**Issue by bwomsm1** [YueChen-C/py-ios-device#81]
I am trying to install certificate with the following code:
```
        cer = '-----BEGIN CERTIFICATE-----rOFP9NZCKjpHxiP1EgbZ7Aj8OfTTXMHYzhVejNK6LBS2X-----END CERTIFICATE-----'
        message_bytes = cer.encode('ascii')
        base64_bytes = base64.b64encode(message_bytes)
        base64_message = base64_bytes.decode('ascii')

       response = self.driver_.execute_script(
            'mobile: installCertificate', {"content": base64_message}
        )
```
The action does working correctly and I am able to see that message on my iPhone device:
![Screenshot 2022-12-12 at 10 34 05](https://user-images.githubusercontent.com/5571230/206998501-ae923878-6fae-4668-9bf6-c27c3ca26d9a.png)

But it does not really help me in my scenario since that the profile is only being downloaded but not installed, in order to install I need to got to the iPhone settings and install the downloaded certificate manually 

### Expected Behavior

certificate should be downloaded and installed 

### Minimal Reproducible Example

```
        cer = '-----BEGIN CERTIFICATE-----rOFP9NZCKjpHxiP1EgbZ7Aj8OfTTXMHYzhVejNK6LBS2X-----END CERTIFICATE-----'
        message_bytes = cer.encode('ascii')
        base64_bytes = base64.b64encode(message_bytes)
        base64_message = base64_bytes.decode('ascii')

       response = self.driver_.execute_script(
            'mobile: installCertificate', {"content": base64_message}
        )
```

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/certificate.log

**Comment by bwomsm1** [comment]
@YueChen-C can you please help with that issue? 
Thanks!

**Comment by YueChen-C** [comment]
I haven't found a better way. Installing the certificate requires very high system permissions

**Comment by bwomsm1** [comment]
thanks @YueChen-C for your response. 
Can we say that install is currently not supported with this tool?

**Comment by pimterry** [comment]
@bwomsm1 I'm also hitting this issue. If you find any way to automatically install a certificate like this, with py-ios-device or any other tool, do please share it here!

**Comment by bwomsm1** [comment]
Thanks, I will.
