### ISSUE TITLE
无法获取高帧(90,120)游戏的FPS

### ISSUE THREAD

**Issue by xlhe3** [YueChen-C/py-ios-device#83]

**Comment by YueChen-C** [comment]
只有 13 14 pro 这种能开到 120 帧，其他 iPhone 最高屏幕帧率也就60。而且获取到的也是屏幕刷新帧率，而不是游戏帧率。

**Comment by homurahomu1** [comment]
我用iPhone13ProMax也是不可以看见比60FPS更高的帧数。。。
