### ISSUE TITLE
通过命令获取的内存和cpu 数据， 对内存与cpu 单位不大理解

### ISSUE THREAD

**Issue by NISHAYANI** [YueChen-C/py-ios-device#85]

**Comment by NISHAYANI** [comment]
数据 [('WeChat', {'cpuUsage': 0.036558268613227536, 'memVirtualSize': 2179284992, 'name': 'WeChat', 'pid': 99269})] 
则 memVirtualSize 和 cpuUsage 是多少呢，在性能测试报告中如何描述该数据

**Comment by YueChen-C** [comment]
physFootprint 是真实消耗内存 ，cpuUsage 就是cpu 使用数据，不过在 ios 14 以下需要 *40
