### ISSUE TITLE
how to get response of whether launch app is successful or failed ?

### ISSUE THREAD

**Issue by mike1023** [YueChen-C/py-ios-device#86]

**Comment by YueChen-C** [comment]
If it starts successfully, it will return to the application pid

**Comment by YueChen-C** [comment]
Failure will be logged for example 
`{'$class': 'NSError', 'domain': 'com.apple.dt.deviceprocesscontrolservice', 'userinfo': {'NSLocalizedRecoverySuggestion': "The app must be debuggable and signed with 'get-task-allow'.", 'NSLocalizedDescription': 'Permission to debug cn.xxx.xxx was denied.', 'NSLocalizedFailureReason': 'Unable to acquire task port for PID: 35970'}, 'code': 2}`
