### ISSUE TITLE
appName is truncated for longer app names

### ISSUE THREAD

**Issue by sanidhya-saraswat** [YueChen-C/py-ios-device#88]
For the command `pyidevice instruments notifications`, it seems like the `appName` key has a maxLength. For some apps, the `appName` is truncated.

For eg,
`[{'mach_absolute_time': 2954262748551, 'execName': '/private/var/containers/Bundle/Application/3518003B-CDCC-4347-8169-381C22F73F9A/Music Speed Changer.app', 'appName': 'Music Speed Cha', 'pid': 412, 'state_description': 'Suspended'}]`

**Comment by YueChen-C** [comment]
![image](https://user-images.githubusercontent.com/12081262/217504159-31953493-8f22-45ec-a070-b88ad4c94dd4.png)

It seems that maxLength is 15

**Comment by sanidhya-saraswat** [comment]
is it fixable?

**Comment by sanidhya-saraswat** [comment]
Unrelated point. Can we get `timestamp` instead of `mach_absolute_time`? Not sure how to convert `mach_absolute_time` to date/time .

**Comment by YueChen-C** [comment]
`mach_absolute_time ` cannot be directly converted to `timestamp`, it is only used for difference calculation

**Comment by YueChen-C** [comment]
cli: v.2.3.12
