### ISSUE TITLE
Anyway to get device lock state?

### ISSUE THREAD

**Issue by sanidhya-saraswat** [YueChen-C/py-ios-device#91]
Event: `com.apple.springboard.lockstate`

Can I get it using `rpc` call or some other way ?

**Comment by YueChen-C** [comment]
I don't know how to get it directly. But you can get notification information through `NotificationProxyService`

**Comment by sanidhya-saraswat** [comment]
True, I was able to get notifications through the `NotificationProxyService`. But the notifications come, when the lock state changes. I want to know the current lock state.

I found this online: `UIApplication.shared.isProtectedDataAvailable` to get the lock state. Not sure how to call it.

**Comment by YueChen-C** [comment]
@khrithik96 That's great
