### ISSUE TITLE
Simulator IOS devices communicate with py-ios-device

### ISSUE THREAD

**Issue by yabostone** [YueChen-C/py-ios-device#94]
Hello,I'm a new user  to capture some ios devices's data messages,while When I use IOS simulator, I did not get any devices udid to step into next example command.
The code show it use usbmux to receive data and control true devices.
Is it possible to use IOS simulator to achieve these function?

**Comment by YueChen-C** [comment]
Only support real devices. The simulator does not use usbmux

**Comment by yabostone** [comment]
Thank you for you advise~~~I had already  purchase a second-hand iphone device for test.~~~~
