### ISSUE TITLE
Anyway to get app size ?

### ISSUE THREAD

**Issue by sanidhya-saraswat** [YueChen-C/py-ios-device#98]

**Comment by khrithik96** [comment]
We get App's size data in Settings App - `General` -> `iPhone Storage`. 
Is there any way we can access this data? @YueChen-C

**Comment by YueChen-C** [comment]
@sanidhya-saraswat @khrithik96  We can get the app size by setting the ClientOptions parameter


```
options = {
    'ReturnAttributes': ['CFBundleIdentifier', 'StaticDiskUsage', 'DynamicDiskUsage'],
    'ApplicationType': 'User'
}
InstallationProxyService().browse(options=options)
```

**Comment by khrithik96** [comment]
Thanks. This is working.
